apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-virtualservice-from-ingress
spec:
  background: false
  rules:
    - name: generate-virtualservice
      match:
        resources:
          kinds:
            - Ingress
      generate:
        generateExisting: true
        kind: VirtualService
        apiVersion: networking.istio.io/v1
        name: "{{ request.object.metadata.name }}-vs"
        namespace: "{{ request.object.metadata.namespace }}"
        synchronize: true
        data:
          spec:
            hosts:
              - "{{ request.object.spec.rules[0].host }}"
            gateways:
              - "istio-ingress/istio-gateway"
            http:
              - match:
                  - uri:
                      prefix: "/"
                route:
                  - destination:
                      host: "{{ request.object.spec.rules[0].http.paths[0].backend.service.name }}"
                      port:
                        number: "{{ request.object.spec.rules[0].http.paths[0].backend.service.port.number || `80` }}"
