version: "3"

vars:
  CLUSTER_NAME: "kyverno-spike"
  METALLB_CONFIG: "./manifests/metallb-config.yaml"

includes:
  helm:
    dir: scripts
    taskfile: scripts/Taskfile.yaml
  manifests:
    dir: scripts/manifests
    taskfile: scripts/manifests/Taskfile.yaml
  policy-test:
    dir: scripts/testing/test-ingress-to-virtual-service-policy
    taskfile: scripts/testing/test-ingress-to-virtual-service-policy/Taskfile.yaml

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task --list-all
