version: "3"

vars:
  CLUSTER_NAME: "kyverno-spike"
  METALLB_CONFIG: "./manifests/metallb-config.yaml"

  TEST_RELEASE_NAME: "nginx-app"
  TEST_NAMESPACE: "nginx-app"

includes:
  cluster:
    dir: scripts
    taskfile: scripts/Taskfile.yaml
  manifests:
    dir: scripts/manifests
    taskfile: scripts/manifests/Taskfile.yaml
  policy-test:
    dir: scripts/testing/test-ingress-to-virtual-service-policy
    taskfile: scripts/testing/test-ingress-to-virtual-service-policy/Taskfile.yaml

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task --list-all

  quickstart:
    desc: "Creates the cluster, installs all of the dependencies, configures MetaLB and Istio, installs the fallback app, installs the Kyverno helm chart, adds the policies, and tests the policies"
    cmds:
      - task: cluster:delete
        quiet: true
        ignore_error: true

      - task: cluster:create
        quiet: true

      - task: policy-test:setup

      - task: policy-test:run
        ignore_error: true
    quiet: true
  
  clean:
    desc: "Deletes the cluster"
    cmds:
      - task cluster:delete
    quiet: true
