version: "3"

tasks:
  setup:
    desc: "Run the policy test setup: Creates an Argo app that installs Nginx with an ingress"
    cmds:
      - helm upgrade --install --wait {{ .TEST_RELEASE_NAME }} . -n {{ .TEST_NAMESPACE }} --create-namespace
    aliases:
      - deploy-nginx-app

  describe:
    desc: "Describe the policy test setup"
    cmds:
      - kubectl describe app {{ .TEST_RELEASE_NAME }} -n {{ .TEST_NAMESPACE }}
      - kubectl get all -n {{ .TEST_NAMESPACE }}


  run:
    desc: "Run the policy test helm tests"
    cmds:
      - helm test {{ .TEST_RELEASE_NAME }} -n {{ .TEST_NAMESPACE }}
    aliases:
      - tests
      - test

  teardown:
    desc: "Run the policy test teardown"
    cmds:
      - helm uninstall {{ .TEST_RELEASE_NAME }} -n {{ .TEST_NAMESPACE }}
      - kubectl delete namespace {{ .TEST_NAMESPACE }}
    aliases:
      - cleanup
