---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-gateway-cert
  namespace: istio-ingress
spec:
  secretName: istio-ingressgateway-certs
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: "kyverno-spike.test"
  dnsNames:
    - "kyverno-spike.test"
    - "*.kyverno-spike.test"
  duration: 8760h # 1 year (adjust as needed)
  renewBefore: 720h # Renew 30 days before expiry
  privateKey:
    algorithm: RSA
    size: 2048
