version: "3"

tasks:
  fallback:
    desc: "Install the fallback app"
    cmds:
      - kubectl apply -f fallback.yaml

  kyverno:
    desc: "Install the Kyverno policy"
    cmds:
      - kubectl apply -f kyverno-policies
